# Generated by Django 2.2.7 on 2019-11-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_sotck_daily_closing',
            fields=[
                ('st_date', models.PositiveIntegerField(db_column='st_date', primary_key=True, serialize=False)),
                ('st_stockno', models.CharField(blank=True, db_column='st_stockno', max_length=20, null=True, unique=True)),
                ('st_stockname', models.CharField(blank=True, db_column='st_stockname', max_length=20, null=True, unique=True)),
                ('transaction_stockamount', models.BigIntegerField(blank=True, db_column='transaction_stockamount', null=True)),
                ('transaction_piecesamount', models.BigIntegerField(blank=True, db_column='transaction_piecesamount', null=True)),
                ('transaction_money', models.BigIntegerField(blank=True, db_column='transaction_money', null=True)),
                ('st_open', models.BigIntegerField(blank=True, db_column='st_open', null=True)),
                ('st_high', models.BigIntegerField(blank=True, db_column='st_high', null=True)),
                ('st_low', models.BigIntegerField(blank=True, db_column='st_low', null=True)),
                ('st_close', models.BigIntegerField(blank=True, db_column='st_close', null=True)),
            ],
            options={
                'db_table': 'all_sotck_daily_closing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('stockid', models.PositiveIntegerField(db_column='StockID', primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, db_column='Abbreviation', max_length=10, null=True, unique=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=128, null=True, unique=True)),
                ('employees', models.PositiveIntegerField(blank=True, db_column='Employees', null=True)),
                ('capital', models.BigIntegerField(blank=True, db_column='Capital', null=True)),
                ('industryname', models.CharField(db_column='IndustryName', max_length=16)),
                ('listeddate', models.CharField(blank=True, db_column='ListedDate', max_length=45, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
    ]
