# Generated by Django 2.2.7 on 2019-11-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Three_legal',
            fields=[
                ('st_date', models.PositiveIntegerField(db_column='st_date', primary_key=True, serialize=False)),
                ('dealer_buy', models.CharField(blank=True, db_column='dealer_buy', max_length=20, null=True, unique=True)),
                ('dealer_sell', models.CharField(blank=True, db_column='dealer_sell', max_length=20, null=True, unique=True)),
                ('dealer_diff', models.BigIntegerField(blank=True, db_column='dealer_diff', null=True)),
                ('dealer_heding_buy', models.BigIntegerField(blank=True, db_column='dealer_heding_buy', null=True)),
                ('dealer_heding_sell', models.BigIntegerField(blank=True, db_column='dealer_heding_sell', null=True)),
                ('dealer_heading_diff', models.BigIntegerField(blank=True, db_column='dealer_heading_diff', null=True)),
                ('it_buy', models.BigIntegerField(blank=True, db_column='it_buy', null=True)),
                ('it_sell', models.BigIntegerField(blank=True, db_column='it_sell', null=True)),
                ('it_diff', models.BigIntegerField(blank=True, db_column='it_diff', null=True)),
                ('foreign_investor_buy', models.BigIntegerField(blank=True, db_column='foreign_investor_buy', null=True)),
                ('foreign_investor_sell', models.BigIntegerField(blank=True, db_column='foreign_investor_sell', null=True)),
                ('foreign_investor_diff', models.BigIntegerField(blank=True, db_column='foreign_investor_diff', null=True)),
                ('foreign_investor_dealer_buy', models.BigIntegerField(blank=True, db_column='foreign_investor_dealer_buy', null=True)),
                ('foreign_investor_dealer_sell', models.BigIntegerField(blank=True, db_column='foreign_investor_dealer_sell', null=True)),
                ('foreign_investor_dealer_diff', models.BigIntegerField(blank=True, db_column='foreign_investor_dealer_diff', null=True)),
                ('total_buy', models.BigIntegerField(blank=True, db_column='total_buy', null=True)),
            ],
            options={
                'db_table': 'three_legal',
                'managed': False,
            },
        ),
    ]
