# Generated by Django 2.2.7 on 2019-11-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_three_legal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Three_legal_overbuysell',
            fields=[
                ('st_date', models.PositiveIntegerField(db_column='st_date', primary_key=True, serialize=False)),
                ('stockno', models.CharField(blank=True, db_column='stockno', max_length=20, null=True, unique=True)),
                ('stockname', models.CharField(blank=True, db_column='stockname', max_length=20, null=True, unique=True)),
                ('foreign_buy_amount', models.BigIntegerField(blank=True, db_column='foreign_buy_amount', null=True)),
                ('foreign_sell_amount', models.BigIntegerField(blank=True, db_column='foreign_sell_amount', null=True)),
                ('foreign_overbuysell', models.BigIntegerField(blank=True, db_column='foreign_overbuysell', null=True)),
                ('foreign_dealer_buy_amount', models.BigIntegerField(blank=True, db_column='foreign_dealer_buy_amount', null=True)),
                ('foreign_dealer_sell_amount', models.BigIntegerField(blank=True, db_column='foreign_dealer_sell_amount', null=True)),
                ('foreign_dealer_overbuysell', models.BigIntegerField(blank=True, db_column='itforeign_dealer_overbuysell_sell', null=True)),
                ('trust_buy_amount', models.BigIntegerField(blank=True, db_column='trust_buy_amount', null=True)),
                ('trust_sell_amount', models.BigIntegerField(blank=True, db_column='trust_sell_amount', null=True)),
                ('trust_overbuysell', models.BigIntegerField(blank=True, db_column='trust_overbuysell', null=True)),
                ('dealer_overbuysell', models.BigIntegerField(blank=True, db_column='dealer_overbuysell', null=True)),
                ('dealer_buysell_buy_amount', models.BigIntegerField(blank=True, db_column='dealer_buysell_buy_amount', null=True)),
                ('dealer_buysell_sell_amount', models.BigIntegerField(blank=True, db_column='dealer_buysell_sell_amount', null=True)),
                ('dealer_buysell_overbuysell', models.BigIntegerField(blank=True, db_column='dealer_buysell_overbuysell', null=True)),
                ('dealer_hedging_buy_amount', models.BigIntegerField(blank=True, db_column='dealer_hedging_buy_amount', null=True)),
                ('dealer_hedging_sell_amount', models.BigIntegerField(blank=True, db_column='dealer_hedging_sell_amount', null=True)),
                ('dealer_hedging_overbuysell', models.BigIntegerField(db_column='dealer_hedging_overbuysell')),
                ('three_legal_overbuysell', models.BigIntegerField(db_column='three_legal_overbuysell')),
            ],
            options={
                'db_table': 'three_legal_overbuysell',
                'managed': False,
            },
        ),
    ]
