# Generated by Django 2.2.7 on 2019-11-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_three_legal_overbuysell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wespai_p49048',
            fields=[
                ('st_date', models.PositiveIntegerField(db_column='st_date', primary_key=True, serialize=False)),
                ('st_stockno', models.CharField(blank=True, db_column='st_stockno', max_length=20, null=True, unique=True)),
                ('st_stockname', models.CharField(blank=True, db_column='st_stockname', max_length=20, null=True, unique=True)),
                ('st_stockprice', models.BigIntegerField(blank=True, db_column='st_stockprice', null=True)),
                ('director_shareholding', models.BigIntegerField(blank=True, db_column='director_shareholding', null=True)),
                ('foreign_shareholding', models.BigIntegerField(blank=True, db_column='foreign_shareholding', null=True)),
                ('trust_shareholding', models.BigIntegerField(blank=True, db_column='trust_shareholding', null=True)),
                ('st_volume', models.BigIntegerField(blank=True, db_column='st_volume', null=True)),
                ('st_three_buysell', models.BigIntegerField(blank=True, db_column='st_three_buysell', null=True)),
                ('issued_number', models.BigIntegerField(blank=True, db_column='issued_number', null=True)),
                ('amount_of_capital', models.BigIntegerField(blank=True, db_column='amount_of_capital', null=True)),
                ('trust_buysell', models.BigIntegerField(blank=True, db_column='trust_buysell', null=True)),
                ('foreign_buysell', models.BigIntegerField(blank=True, db_column='foreign_buysell', null=True)),
                ('industry_type', models.CharField(blank=True, db_column='industry_type', max_length=20, null=True, unique=True)),
                ('trust_amount_day', models.BigIntegerField(blank=True, db_column='trust_amount_day', null=True)),
                ('trust_stock_quantity', models.BigIntegerField(blank=True, db_column='trust_stock_quantity', null=True)),
                ('trust_stock_totalAmount', models.BigIntegerField(blank=True, db_column='trust_stock_totalAmount', null=True)),
                ('trust_buysell_shareCapital_ratio', models.BigIntegerField(blank=True, db_column='trust_buysell_shareCapital_ratio', null=True)),
                ('foreign_amount_day', models.BigIntegerField(blank=True, db_column='foreign_amount_day', null=True)),
                ('foreign_stock_quantity', models.BigIntegerField(blank=True, db_column='foreign_stock_quantity', null=True)),
                ('foreign_stock_totalAmount', models.BigIntegerField(blank=True, db_column='foreign_stock_totalAmount', null=True)),
                ('foreign_buysell_shareCapital_ratio', models.BigIntegerField(blank=True, db_column='foreign_buysell_shareCapital_ratio', null=True)),
            ],
            options={
                'db_table': 'wespai_p49048',
                'managed': False,
            },
        ),
    ]
