# Generated by Django 2.2.7 on 2019-12-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_wespai_p49048'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_stock_daily_closing',
            fields=[
                ('st_date', models.PositiveIntegerField(db_column='st_date', primary_key=True, serialize=False)),
                ('st_stockno', models.CharField(blank=True, db_column='st_stockno', max_length=20, null=True, unique=True)),
                ('st_stockname', models.CharField(blank=True, db_column='st_stockname', max_length=20, null=True, unique=True)),
                ('st_stockprice', models.BigIntegerField(blank=True, db_column='st_stockprice', null=True)),
                ('transaction_stockamount', models.BigIntegerField(blank=True, db_column='transaction_stockamount', null=True)),
                ('transaction_piecesamount', models.BigIntegerField(blank=True, db_column='transaction_piecesamount', null=True)),
                ('transaction_money', models.BigIntegerField(blank=True, db_column='transaction_money', null=True)),
                ('st_open', models.BigIntegerField(blank=True, db_column='st_open', null=True)),
                ('st_high', models.BigIntegerField(blank=True, db_column='st_high', null=True)),
                ('st_low', models.BigIntegerField(blank=True, db_column='st_low', null=True)),
                ('st_close', models.BigIntegerField(blank=True, db_column='st_close', null=True)),
                ('change_extent', models.BigIntegerField(blank=True, db_column='change_extent', null=True)),
            ],
            options={
                'db_table': 'all_stock_daily_closing',
                'managed': False,
            },
        ),
    ]
