# Generated by Django 2.2.7 on 2019-12-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_all_stock_daily_closing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_warrant',
            fields=[
                ('st_date', models.PositiveIntegerField(db_column='st_date', primary_key=True, serialize=False)),
                ('st_stockno_call_warrant', models.CharField(blank=True, db_column='st_stockno_call_warrant', max_length=20, null=True, unique=True)),
                ('st_stockname_call_warrant', models.CharField(blank=True, db_column='st_stockname_call_warrant', max_length=20, null=True, unique=True)),
                ('st_numberOfShares_call_warrant', models.BigIntegerField(blank=True, db_column='st_numberOfShares_call_warrant', null=True)),
                ('st_count_call_warrant', models.BigIntegerField(blank=True, db_column='st_count_call_warrant', null=True)),
                ('st_amount_call_warrant', models.BigIntegerField(blank=True, db_column='st_amount_call_warrant', null=True)),
                ('st_close_call_warrant', models.DecimalField(db_column='st_close_call_warrant', decimal_places=2, max_digits=5, null=True)),
                ('st_stockno', models.CharField(blank=True, db_column='st_stockno', max_length=20, null=True, unique=True)),
                ('st_stockname', models.CharField(blank=True, db_column='st_stockname', max_length=20, null=True, unique=True)),
                ('st_close', models.DecimalField(db_column='st_close', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'call_warrant',
                'managed': False,
            },
        ),
    ]
